list = ['a','b', 2, 5,15.5,'Genial']
print(list)
list.append('Siempre es tiempo de aprender')
print(list)
list.insert(5,'Simple,Poderoso')
print(list)
list.remove('Genial')
print(list)
list.pop()
print(list)
list2 = [1,5,8,9,3,7,75,99,66,33,22]
list2.sort()
print(list2)
letras = ['z','a','g','p']
letras.sort()
print(letras)
list2.append(letras)
print(list2)

papel = []
papel.insert(0,1)
print(papel)
papel.insert(1,2)
print(papel)
papel.insert(2,3)
print(papel)
papel.insert(3,4)
print(papel)
papel.insert(4,5)
print(papel)
papel.insert(5,'Genial')
print(papel)